version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "package-lock.json" }}
            - v1-
      - run:
          name: "Say hello"
          command: "echo Hello, World"
      - save_cache:
          keys:
            - v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    steps:
      - run: find .
      - attach_workspace:
          at: ~/workspace
      - run:
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="#SONAR_TOKEN" \
            -Dsonar.branch.name="$CIRCLE_BRANCH" Â  
            -Dsonar.sources="."

workflows:
  build-and-test:
    jobs:
      - say-hello
      - sonarqube
